# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - run: npm i -g bower
      - run: npm i
      - run: bower install
      - run: npx grunt build-chrome
      - uses: actions/upload-artifact@v2
        with:
          name: twitter-blockchain
          path: |
            blockchain.zip
